name: goop
description: A new Flutter project.

publish_to: 'none'

version: 21.09+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.12+4
  uuid:
  http:
  rxdart:
  flutter_mobx:
  mobx:
  flutter_map:
  cpf_cnpj_validator:
  email_validator: ^2.0.1
  flutter_image_compress: ^1.0.0
  mask_text_input_formatter: ^1.2.1
  otp_text_field: ^1.0.2
  flutter_svg:
  image_picker:
  provider:
  geolocator:
  camera:
  camera_camera:
  cupertino_icons: ^1.0.2
  url_launcher: ^5.7.10
  flutter_webview_plugin: ^0.4.0
  intl: ^0.17.0
  encrypt: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen:
  build_runner:
  flutter_native_splash: ^1.2.1

flutter_native_splash:
  color: '#DF0047'
  image: 'assets/images/logo.png'
  android: true
  ios: true
  web: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/jsons/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
