name: goop
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.12+4
  uuid: ^2.2.2
  http: ^0.12.2
  rxdart: ^0.25.0
  flutter_mobx: ^1.1.0+2
  mobx: ^1.2.1+4
  data_connection_checker:
  cpf_cnpj_validator: ^1.0.5
  email_validator: ^1.0.6
  mask_text_input_formatter: ^1.2.1
  flutter_svg: ^0.19.3
  image_picker: ^0.6.7+22
  provider: ^4.3.3
  latlng: ^0.0.2
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^1.1.2
  build_runner:
  # build_runner: ^1.12.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
